# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: index
  joint_model_group_pose: index
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - forth_finger_base_joint
    - forth_finger_2_joint
    - forth_finger_3_joint
    - index_phalanx_base_joint
    - index_phalanx_2_joint
    - index_phalanx_3_joint
    - second_finger_phalanx_base_joint
    - second_finger_phalanx_2_joint
    - second_finger_phalanx_3_joint
    - third_finger_base_joint
    - third_finger_2_joint
    - third_finger_3_joint
    - thumb_finger_base_joint
    - thumb_finger_2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
hand_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - index_phalanx_base_joint
    - index_phalanx_2_joint
    - index_phalanx_3_joint
    - second_finger_phalanx_base_joint
    - second_finger_phalanx_2_joint
    - second_finger_phalanx_3_joint
    - third_finger_base_joint
    - third_finger_2_joint
    - third_finger_3_joint
    - forth_finger_base_joint
    - forth_finger_2_joint
    - forth_finger_3_joint
    - thumb_finger_base_joint
    - thumb_finger_2_joint
  gains:
    index_phalanx_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    index_phalanx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    index_phalanx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    second_finger_phalanx_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    second_finger_phalanx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    second_finger_phalanx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    third_finger_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    third_finger_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    third_finger_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forth_finger_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forth_finger_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forth_finger_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    thumb_finger_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    thumb_finger_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1