# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: leg1
  joint_model_group_pose: leg1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - root_link_1_joint
    - long_link_1_joint
    - link_1_joint
    - leaf_link_1_joint
    - root_link_2_joint
    - long_link_2_joint
    - link_2_joint
    - leaf_link_2_joint
    - root_link_3_joint
    - long_link_3_joint
    - link_3_joint
    - leaf_link_3_joint
    - root_link_4_joint
    - long_link_4_joint
    - link_4_joint
    - leaf_link_4_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: leg1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - root_link_1_joint
      - long_link_1_joint
      - link_1_joint
      - leaf_link_1_joint
  - name: leg2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - root_link_2_joint
      - long_link_2_joint
      - link_2_joint
      - leaf_link_2_joint
  - name: leg3_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - root_link_3_joint
      - long_link_3_joint
      - link_3_joint
      - leaf_link_3_joint
  - name: leg4_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - root_link_4_joint
      - long_link_4_joint
      - link_4_joint
      - leaf_link_4_joint
  - name: ee1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      leaf_link_1_joint
  - name: ee2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      leaf_link_2_joint
  - name: ee3_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      leaf_link_3_joint
  - name: ee4_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      leaf_link_4_joint